#define LPAREN                           1
#define RPAREN                           2
#define LET                              3
#define STRING                           4
#define EQUAL                            5
#define PLUS                             6
#define MINUS                            7
#define DIV                              8
#define MUL                              9
#define GRT                             10
#define LST                             11
#define NUMBER                          12
#define FALSE                           13
#define TRUE                            14